// Code generated by abigen — DO NOT EDIT.
//
// Source contract : contracts/EquipmentRegistry.sol
// Regenerate with : make bindings  (see Makefile)
package contracts

import (
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// EquipmentData mirrors the Equipment struct in IEquipmentRegistry.sol.
// Status enum values: 0=Registered, 1=ShopInspected, 2=Certified, 3=Active.
type EquipmentData struct {
	EquipmentId         *big.Int       `abi:"equipmentId"`
	Crn                 string         `abi:"crn"`
	ANumber             string         `abi:"aNumber"`
	MdrHash             [32]byte       `abi:"mdrHash"`
	Mawp                *big.Int       `abi:"mawp"`
	Manufacturer        common.Address `abi:"manufacturer"`
	RegisteredAt        *big.Int       `abi:"registeredAt"`
	ShopInspector       common.Address `abi:"shopInspector"`
	ShopInspectedAt     *big.Int       `abi:"shopInspectedAt"`
	CertificateIssuer   common.Address `abi:"certificateIssuer"`
	CertificateIssuedAt *big.Int       `abi:"certificateIssuedAt"`
	Status              uint8          `abi:"status"`
}

// EquipmentRegistryABI is the JSON ABI of the deployed EquipmentRegistry contract.
const EquipmentRegistryABI = `[
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {"internalType": "string",  "name": "crn",     "type": "string"},
      {"internalType": "bytes32", "name": "mdrHash", "type": "bytes32"},
      {"internalType": "uint256", "name": "mawp",    "type": "uint256"}
    ],
    "name": "registerEquipment",
    "outputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "signShopInspection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {"internalType": "uint256", "name": "equipmentId", "type": "uint256"},
      {"internalType": "string",  "name": "aNumber",     "type": "string"}
    ],
    "name": "issueCertificate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "activateEquipment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "getEquipment",
    "outputs": [{
      "components": [
        {"internalType": "uint256",  "name": "equipmentId",         "type": "uint256"},
        {"internalType": "string",   "name": "crn",                 "type": "string"},
        {"internalType": "string",   "name": "aNumber",             "type": "string"},
        {"internalType": "bytes32",  "name": "mdrHash",             "type": "bytes32"},
        {"internalType": "uint256",  "name": "mawp",                "type": "uint256"},
        {"internalType": "address",  "name": "manufacturer",        "type": "address"},
        {"internalType": "uint256",  "name": "registeredAt",        "type": "uint256"},
        {"internalType": "address",  "name": "shopInspector",       "type": "address"},
        {"internalType": "uint256",  "name": "shopInspectedAt",     "type": "uint256"},
        {"internalType": "address",  "name": "certificateIssuer",   "type": "address"},
        {"internalType": "uint256",  "name": "certificateIssuedAt", "type": "uint256"},
        {"internalType": "uint8",    "name": "status",              "type": "uint8"}
      ],
      "internalType": "struct IEquipmentRegistry.Equipment",
      "name": "",
      "type": "tuple"
    }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "isCertified",
    "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "equipmentCount",
    "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "stateMutability": "view",
    "type": "function"
  }
]`

// ──────────────────────────────────────────────────────────────────────────────
// Binding structs
// ──────────────────────────────────────────────────────────────────────────────

type EquipmentRegistry struct {
	EquipmentRegistryCaller
	EquipmentRegistryTransactor
	EquipmentRegistryFilterer
}

type EquipmentRegistryCaller struct {
	contract *bind.BoundContract
}

type EquipmentRegistryTransactor struct {
	contract *bind.BoundContract
}

type EquipmentRegistryFilterer struct {
	contract *bind.BoundContract
}

// NewEquipmentRegistry creates a Go binding to the deployed contract at address.
func NewEquipmentRegistry(address common.Address, backend bind.ContractBackend) (*EquipmentRegistry, error) {
	parsed, err := abi.JSON(strings.NewReader(EquipmentRegistryABI))
	if err != nil {
		return nil, err
	}
	contract := bind.NewBoundContract(address, parsed, backend, backend, backend)
	return &EquipmentRegistry{
		EquipmentRegistryCaller:     EquipmentRegistryCaller{contract: contract},
		EquipmentRegistryTransactor: EquipmentRegistryTransactor{contract: contract},
		EquipmentRegistryFilterer:   EquipmentRegistryFilterer{contract: contract},
	}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Transactor methods
// ──────────────────────────────────────────────────────────────────────────────

// RegisterEquipment calls registerEquipment(string,bytes32,uint256).
// mdrHash must be a 32-byte array, e.g. crypto.Keccak256Hash(doc).
func (t *EquipmentRegistryTransactor) RegisterEquipment(
	opts *bind.TransactOpts,
	crn string,
	mdrHash [32]byte,
	mawp *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "registerEquipment", crn, mdrHash, mawp)
}

// SignShopInspection calls signShopInspection(uint256). Caller must hold SCO_ROLE.
func (t *EquipmentRegistryTransactor) SignShopInspection(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "signShopInspection", equipmentId)
}

// IssueCertificate calls issueCertificate(uint256,string). Caller must hold ABSA_ROLE.
func (t *EquipmentRegistryTransactor) IssueCertificate(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
	aNumber string,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "issueCertificate", equipmentId, aNumber)
}

// ActivateEquipment calls activateEquipment(uint256). Caller must hold ABSA_ROLE.
func (t *EquipmentRegistryTransactor) ActivateEquipment(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "activateEquipment", equipmentId)
}

// GetEquipment calls getEquipment(uint256) and unpacks the Equipment tuple.
func (c *EquipmentRegistryCaller) GetEquipment(opts *bind.CallOpts, equipmentId *big.Int) (EquipmentData, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getEquipment", equipmentId); err != nil {
		return EquipmentData{}, err
	}
	result := abi.ConvertType(out[0], new(EquipmentData)).(*EquipmentData)
	return *result, nil
}

// IsCertified calls isCertified(uint256). Returns true for Certified or Active status.
func (c *EquipmentRegistryCaller) IsCertified(opts *bind.CallOpts, equipmentId *big.Int) (bool, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "isCertified", equipmentId); err != nil {
		return false, err
	}
	return *abi.ConvertType(out[0], new(bool)).(*bool), nil
}

// EquipmentCount returns the current total number of registered equipment assets.
func (c *EquipmentRegistryCaller) EquipmentCount(opts *bind.CallOpts) (*big.Int, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "equipmentCount"); err != nil {
		return nil, err
	}
	return *abi.ConvertType(out[0], new(*big.Int)).(**big.Int), nil
}
