// Code generated by abigen — DO NOT EDIT.
//
// Source contract : contracts/EquipmentRegistry.sol
// Regenerate with : make bindings  (see Makefile)
//
// This file was hand-authored to match the expected abigen output until
// `make bindings` has been run against the deployed contract ABIs.
package contracts

import (
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// Suppress unused-import errors until event subscriptions are wired up.
var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// EquipmentData mirrors the Equipment struct defined in IEquipmentRegistry.sol.
// Field names follow Go conventions (PascalCase); abigen maps them from the
// Solidity camelCase names using the ABI component names.
type EquipmentData struct {
	AssetId           string
	Crn               string
	ANumber           string
	MdrHash           string
	CurrentOperator   common.Address
	CertificateIssued bool
	Compliant         bool
	Exists            bool
}

// EquipmentRegistryABI is the JSON ABI of the deployed EquipmentRegistry contract.
// It is used by go-ethereum's ABI encoder/decoder to translate between Go types
// and the EVM's binary encoding (ABI encoding).
const EquipmentRegistryABI = `[
  {
    "inputs": [
      {"internalType": "string",  "name": "assetId",         "type": "string"},
      {"internalType": "string",  "name": "crn",             "type": "string"},
      {"internalType": "string",  "name": "aNumber",         "type": "string"},
      {"internalType": "string",  "name": "mdrHash",         "type": "string"},
      {"internalType": "address", "name": "initialOperator", "type": "address"}
    ],
    "name": "registerEquipment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {"internalType": "string", "name": "assetId", "type": "string"},
      {"internalType": "bool",   "name": "issued",  "type": "bool"}
    ],
    "name": "setCertificateIssued",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {"internalType": "string", "name": "assetId",   "type": "string"},
      {"internalType": "bool",   "name": "compliant", "type": "bool"}
    ],
    "name": "setComplianceStatus",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "string", "name": "assetId", "type": "string"}],
    "name": "getEquipment",
    "outputs": [{
      "components": [
        {"internalType": "string",  "name": "assetId",           "type": "string"},
        {"internalType": "string",  "name": "crn",               "type": "string"},
        {"internalType": "string",  "name": "aNumber",           "type": "string"},
        {"internalType": "string",  "name": "mdrHash",           "type": "string"},
        {"internalType": "address", "name": "currentOperator",   "type": "address"},
        {"internalType": "bool",    "name": "certificateIssued", "type": "bool"},
        {"internalType": "bool",    "name": "compliant",         "type": "bool"},
        {"internalType": "bool",    "name": "exists",            "type": "bool"}
      ],
      "internalType": "struct IEquipmentRegistry.Equipment",
      "name": "",
      "type": "tuple"
    }],
    "stateMutability": "view",
    "type": "function"
  }
]`

// ──────────────────────────────────────────────────────────────────────────────
// Binding structs (mirrors the abigen output pattern)
// ──────────────────────────────────────────────────────────────────────────────

// EquipmentRegistry is an auto-generated Go binding for the EquipmentRegistry contract.
// It bundles a Caller (for read-only eth_call) and a Transactor (for state-changing txs).
type EquipmentRegistry struct {
	EquipmentRegistryCaller
	EquipmentRegistryTransactor
	EquipmentRegistryFilterer
}

// EquipmentRegistryCaller wraps the read-only contract methods.
type EquipmentRegistryCaller struct {
	contract *bind.BoundContract
}

// EquipmentRegistryTransactor wraps state-changing contract methods.
type EquipmentRegistryTransactor struct {
	contract *bind.BoundContract
}

// EquipmentRegistryFilterer is a placeholder for event log filtering (future use).
type EquipmentRegistryFilterer struct {
	contract *bind.BoundContract
}

// NewEquipmentRegistry creates a Go binding to the deployed contract at address.
// backend must satisfy bind.ContractBackend (any *ethclient.Client does).
func NewEquipmentRegistry(address common.Address, backend bind.ContractBackend) (*EquipmentRegistry, error) {
	parsed, err := abi.JSON(strings.NewReader(EquipmentRegistryABI))
	if err != nil {
		return nil, err
	}
	// bind.NewBoundContract wires the ABI and backend together.  The same
	// underlying *BoundContract is shared across Caller, Transactor, and Filterer.
	contract := bind.NewBoundContract(address, parsed, backend, backend, backend)
	return &EquipmentRegistry{
		EquipmentRegistryCaller:     EquipmentRegistryCaller{contract: contract},
		EquipmentRegistryTransactor: EquipmentRegistryTransactor{contract: contract},
		EquipmentRegistryFilterer:   EquipmentRegistryFilterer{contract: contract},
	}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Transactor methods — send signed transactions to the network
// ──────────────────────────────────────────────────────────────────────────────

// RegisterEquipment calls the registerEquipment(string,string,string,string,address)
// function on the deployed contract.  auth must be built by SepoliaClient.GetAuthTransactor.
func (t *EquipmentRegistryTransactor) RegisterEquipment(
	opts *bind.TransactOpts,
	assetId, crn, aNumber, mdrHash string,
	initialOperator common.Address,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "registerEquipment",
		assetId, crn, aNumber, mdrHash, initialOperator)
}

// SetCertificateIssued updates the certificateIssued flag for an asset.
func (t *EquipmentRegistryTransactor) SetCertificateIssued(
	opts *bind.TransactOpts,
	assetId string,
	issued bool,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "setCertificateIssued", assetId, issued)
}

// SetComplianceStatus updates the compliance flag for an asset.
func (t *EquipmentRegistryTransactor) SetComplianceStatus(
	opts *bind.TransactOpts,
	assetId string,
	compliant bool,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "setComplianceStatus", assetId, compliant)
}

// ──────────────────────────────────────────────────────────────────────────────
// Caller methods — free read-only eth_call, never costs gas
// ──────────────────────────────────────────────────────────────────────────────

// GetEquipment calls the view function getEquipment(string) and unpacks the
// returned Equipment tuple into an EquipmentData Go struct.
func (c *EquipmentRegistryCaller) GetEquipment(opts *bind.CallOpts, assetId string) (EquipmentData, error) {
	// go-ethereum's ABI decoder decodes the tuple return value directly into
	// a struct whose field tags match the ABI component names.
	var result struct {
		AssetId           string         `abi:"assetId"`
		Crn               string         `abi:"crn"`
		ANumber           string         `abi:"aNumber"`
		MdrHash           string         `abi:"mdrHash"`
		CurrentOperator   common.Address `abi:"currentOperator"`
		CertificateIssued bool           `abi:"certificateIssued"`
		Compliant         bool           `abi:"compliant"`
		Exists            bool           `abi:"exists"`
	}

	out := []interface{}{&result}
	if err := c.contract.Call(opts, &out, "getEquipment", assetId); err != nil {
		return EquipmentData{}, err
	}

	return EquipmentData{
		AssetId:           result.AssetId,
		Crn:               result.Crn,
		ANumber:           result.ANumber,
		MdrHash:           result.MdrHash,
		CurrentOperator:   result.CurrentOperator,
		CertificateIssued: result.CertificateIssued,
		Compliant:         result.Compliant,
		Exists:            result.Exists,
	}, nil
}
