// Code generated by abigen — DO NOT EDIT.
//
// Source contract : contracts/interfaces/InspectionLog.sol
// Regenerate with : make bindings  (see Makefile)
package contracts

import (
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// InspectionRecord mirrors the InspectionRecord struct in IInspectionLog.sol.
// Result enum values: 0=Pass, 1=Fail.
type InspectionRecord struct {
	InspectionId *big.Int       `abi:"inspectionId"`
	Inspector    common.Address `abi:"inspector"`
	InspectedAt  *big.Int       `abi:"inspectedAt"`
	Result       uint8          `abi:"result"`
	NotesHash    [32]byte       `abi:"notesHash"`
}

// InspectionLogABI is the JSON ABI of the deployed InspectionLog contract.
const InspectionLogABI = `[
  {
    "inputs": [
      {"internalType": "address", "name": "absa",            "type": "address"},
      {"internalType": "address", "name": "",                "type": "address"},
      {"internalType": "uint256", "name": "intervalSeconds", "type": "uint256"}
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {"internalType": "uint256", "name": "equipmentId", "type": "uint256"},
      {"internalType": "uint8",   "name": "result",      "type": "uint8"},
      {"internalType": "bytes32", "name": "notesHash",   "type": "bytes32"}
    ],
    "name": "logInspection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "checkOverdue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "intervalSeconds", "type": "uint256"}],
    "name": "setInspectionInterval",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "isCompliant",
    "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "getInspectionHistory",
    "outputs": [{
      "components": [
        {"internalType": "uint256", "name": "inspectionId", "type": "uint256"},
        {"internalType": "address", "name": "inspector",    "type": "address"},
        {"internalType": "uint256", "name": "inspectedAt",  "type": "uint256"},
        {"internalType": "uint8",   "name": "result",       "type": "uint8"},
        {"internalType": "bytes32", "name": "notesHash",    "type": "bytes32"}
      ],
      "internalType": "struct IInspectionLog.InspectionRecord[]",
      "name": "",
      "type": "tuple[]"
    }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "inspectionInterval",
    "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "name": "lastInspectedAt",
    "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "name": "complianceFlag",
    "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
    "stateMutability": "view",
    "type": "function"
  }
]`

// ──────────────────────────────────────────────────────────────────────────────
// Binding structs
// ──────────────────────────────────────────────────────────────────────────────

type InspectionLog struct {
	InspectionLogCaller
	InspectionLogTransactor
	InspectionLogFilterer
}

type InspectionLogCaller struct {
	contract *bind.BoundContract
}

type InspectionLogTransactor struct {
	contract *bind.BoundContract
}

type InspectionLogFilterer struct {
	contract *bind.BoundContract
}

// NewInspectionLog creates a Go binding to the deployed InspectionLog contract.
func NewInspectionLog(address common.Address, backend bind.ContractBackend) (*InspectionLog, error) {
	parsed, err := abi.JSON(strings.NewReader(InspectionLogABI))
	if err != nil {
		return nil, err
	}
	contract := bind.NewBoundContract(address, parsed, backend, backend, backend)
	return &InspectionLog{
		InspectionLogCaller:     InspectionLogCaller{contract: contract},
		InspectionLogTransactor: InspectionLogTransactor{contract: contract},
		InspectionLogFilterer:   InspectionLogFilterer{contract: contract},
	}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Transactor methods
// ──────────────────────────────────────────────────────────────────────────────

// LogInspection sends a logInspection(uint256,uint8,bytes32) transaction.
// result: 0=Pass, 1=Fail. notesHash: keccak256 of the off-chain notes document.
func (t *InspectionLogTransactor) LogInspection(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
	result uint8,
	notesHash [32]byte,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "logInspection", equipmentId, result, notesHash)
}

// CheckOverdue sends a checkOverdue(uint256) transaction. Caller must hold ABSA_ROLE.
func (t *InspectionLogTransactor) CheckOverdue(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "checkOverdue", equipmentId)
}

// SetInspectionInterval sends a setInspectionInterval(uint256) transaction.
// Caller must hold ABSA_ROLE.
func (t *InspectionLogTransactor) SetInspectionInterval(
	opts *bind.TransactOpts,
	intervalSeconds *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "setInspectionInterval", intervalSeconds)
}

// ──────────────────────────────────────────────────────────────────────────────
// Caller methods
// ──────────────────────────────────────────────────────────────────────────────

// IsCompliant calls isCompliant(uint256). Returns the live compliance flag.
func (c *InspectionLogCaller) IsCompliant(opts *bind.CallOpts, equipmentId *big.Int) (bool, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "isCompliant", equipmentId); err != nil {
		return false, err
	}
	return *abi.ConvertType(out[0], new(bool)).(*bool), nil
}

// GetInspectionHistory calls getInspectionHistory(uint256) and decodes the
// returned tuple[] into a []InspectionRecord slice.
func (c *InspectionLogCaller) GetInspectionHistory(
	opts *bind.CallOpts,
	equipmentId *big.Int,
) ([]InspectionRecord, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getInspectionHistory", equipmentId); err != nil {
		return nil, err
	}
	result := abi.ConvertType(out[0], new([]InspectionRecord)).(*[]InspectionRecord)
	return *result, nil
}

// InspectionInterval returns the current global inspection interval in seconds.
func (c *InspectionLogCaller) InspectionInterval(opts *bind.CallOpts) (*big.Int, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "inspectionInterval"); err != nil {
		return nil, err
	}
	return *abi.ConvertType(out[0], new(*big.Int)).(**big.Int), nil
}

// LastInspectedAt returns the timestamp of the most recent inspection for an asset.
func (c *InspectionLogCaller) LastInspectedAt(opts *bind.CallOpts, equipmentId *big.Int) (*big.Int, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "lastInspectedAt", equipmentId); err != nil {
		return nil, err
	}
	return *abi.ConvertType(out[0], new(*big.Int)).(**big.Int), nil
}
