// Code generated by abigen — DO NOT EDIT.
//
// Source contract : contracts/interfaces/InspectionLog.sol
// Regenerate with : make bindings  (see Makefile)
package contracts

import (
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// Suppress unused-import errors.
var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// InspectionRecord mirrors the InspectionRecord struct in IInspectionLog.sol.
// The `abi` tags must exactly match the Solidity component names.
type InspectionRecord struct {
	InspectionDate *big.Int       `abi:"inspectionDate"`
	Inspector      common.Address `abi:"inspector"`
	Passed         bool           `abi:"passed"`
	Notes          string         `abi:"notes"`
}

// InspectionLogABI is the JSON ABI of the deployed InspectionLog contract.
const InspectionLogABI = `[
  {
    "inputs": [
      {"internalType": "string",  "name": "assetId",        "type": "string"},
      {"internalType": "uint256", "name": "inspectionDate", "type": "uint256"},
      {"internalType": "bool",    "name": "passed",         "type": "bool"},
      {"internalType": "string",  "name": "notes",          "type": "string"}
    ],
    "name": "logInspection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "string", "name": "assetId", "type": "string"}],
    "name": "getInspectionCount",
    "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {"internalType": "string",  "name": "assetId", "type": "string"},
      {"internalType": "uint256", "name": "index",   "type": "uint256"}
    ],
    "name": "getInspectionRecord",
    "outputs": [{
      "components": [
        {"internalType": "uint256", "name": "inspectionDate", "type": "uint256"},
        {"internalType": "address", "name": "inspector",      "type": "address"},
        {"internalType": "bool",    "name": "passed",         "type": "bool"},
        {"internalType": "string",  "name": "notes",          "type": "string"}
      ],
      "internalType": "struct IInspectionLog.InspectionRecord",
      "name": "",
      "type": "tuple"
    }],
    "stateMutability": "view",
    "type": "function"
  }
]`

// ──────────────────────────────────────────────────────────────────────────────
// Binding structs
// ──────────────────────────────────────────────────────────────────────────────

// InspectionLog is the auto-generated Go binding for the InspectionLog contract.
type InspectionLog struct {
	InspectionLogCaller
	InspectionLogTransactor
	InspectionLogFilterer
}

// InspectionLogCaller wraps the read-only methods.
type InspectionLogCaller struct {
	contract *bind.BoundContract
}

// InspectionLogTransactor wraps the state-changing methods.
type InspectionLogTransactor struct {
	contract *bind.BoundContract
}

// InspectionLogFilterer is a placeholder for event subscriptions.
type InspectionLogFilterer struct {
	contract *bind.BoundContract
}

// NewInspectionLog creates a Go binding to the deployed InspectionLog contract.
func NewInspectionLog(address common.Address, backend bind.ContractBackend) (*InspectionLog, error) {
	parsed, err := abi.JSON(strings.NewReader(InspectionLogABI))
	if err != nil {
		return nil, err
	}
	contract := bind.NewBoundContract(address, parsed, backend, backend, backend)
	return &InspectionLog{
		InspectionLogCaller:     InspectionLogCaller{contract: contract},
		InspectionLogTransactor: InspectionLogTransactor{contract: contract},
		InspectionLogFilterer:   InspectionLogFilterer{contract: contract},
	}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Transactor methods
// ──────────────────────────────────────────────────────────────────────────────

// LogInspection sends a logInspection transaction to append an inspection record.
// inspectionDate should be a Unix timestamp (use time.Now().Unix()).
func (t *InspectionLogTransactor) LogInspection(
	opts *bind.TransactOpts,
	assetId string,
	inspectionDate *big.Int,
	passed bool,
	notes string,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "logInspection", assetId, inspectionDate, passed, notes)
}

// ──────────────────────────────────────────────────────────────────────────────
// Caller methods
// ──────────────────────────────────────────────────────────────────────────────

// GetInspectionCount returns the total number of inspection records for assetId.
func (c *InspectionLogCaller) GetInspectionCount(opts *bind.CallOpts, assetId string) (*big.Int, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getInspectionCount", assetId); err != nil {
		return nil, err
	}
	// The ABI decoder puts the uint256 result at index 0 as a *big.Int.
	return *abi.ConvertType(out[0], new(*big.Int)).(**big.Int), nil
}

// GetInspectionRecord returns a single inspection record by index.
func (c *InspectionLogCaller) GetInspectionRecord(
	opts *bind.CallOpts,
	assetId string,
	index *big.Int,
) (InspectionRecord, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getInspectionRecord", assetId, index); err != nil {
		return InspectionRecord{}, err
	}
	result := abi.ConvertType(out[0], new(InspectionRecord)).(*InspectionRecord)
	return *result, nil
}
