// Code generated by abigen — DO NOT EDIT.
//
// Source contract : contracts/OwnershipTransfer.sol
// Regenerate with : make bindings  (see Makefile)
package contracts

import (
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// Suppress unused-import errors.
var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// OwnershipTransferABI is the JSON ABI of the deployed OwnershipTransfer contract.
const OwnershipTransferABI = `[
  {
    "inputs": [{"internalType": "address", "name": "registryAddress", "type": "address"}],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {"internalType": "string",  "name": "assetId",     "type": "string"},
      {"internalType": "address", "name": "newOperator", "type": "address"}
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "string", "name": "assetId", "type": "string"}],
    "name": "canTransfer",
    "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
    "stateMutability": "view",
    "type": "function"
  }
]`

// ──────────────────────────────────────────────────────────────────────────────
// Binding structs
// ──────────────────────────────────────────────────────────────────────────────

// OwnershipTransfer is the auto-generated Go binding for the OwnershipTransfer contract.
type OwnershipTransfer struct {
	OwnershipTransferCaller
	OwnershipTransferTransactor
	OwnershipTransferFilterer
}

// OwnershipTransferCaller wraps the read-only methods.
type OwnershipTransferCaller struct {
	contract *bind.BoundContract
}

// OwnershipTransferTransactor wraps state-changing methods.
type OwnershipTransferTransactor struct {
	contract *bind.BoundContract
}

// OwnershipTransferFilterer is a placeholder for event subscriptions.
type OwnershipTransferFilterer struct {
	contract *bind.BoundContract
}

// NewOwnershipTransfer creates a Go binding to the deployed OwnershipTransfer contract.
func NewOwnershipTransfer(address common.Address, backend bind.ContractBackend) (*OwnershipTransfer, error) {
	parsed, err := abi.JSON(strings.NewReader(OwnershipTransferABI))
	if err != nil {
		return nil, err
	}
	contract := bind.NewBoundContract(address, parsed, backend, backend, backend)
	return &OwnershipTransfer{
		OwnershipTransferCaller:     OwnershipTransferCaller{contract: contract},
		OwnershipTransferTransactor: OwnershipTransferTransactor{contract: contract},
		OwnershipTransferFilterer:   OwnershipTransferFilterer{contract: contract},
	}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Transactor methods
// ──────────────────────────────────────────────────────────────────────────────

// TransferOwnership sends a transferOwnership(string,address) transaction.
// The contract will revert if the asset is not eligible (see CanTransfer).
func (t *OwnershipTransferTransactor) TransferOwnership(
	opts *bind.TransactOpts,
	assetId string,
	newOperator common.Address,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "transferOwnership", assetId, newOperator)
}

// ──────────────────────────────────────────────────────────────────────────────
// Caller methods
// ──────────────────────────────────────────────────────────────────────────────

// CanTransfer calls the canTransfer(string) view function and returns whether
// the asset currently satisfies the transfer preconditions (certificateIssued && compliant).
// This is a free eth_call — it does not consume gas.
func (c *OwnershipTransferCaller) CanTransfer(opts *bind.CallOpts, assetId string) (bool, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "canTransfer", assetId); err != nil {
		return false, err
	}
	return *abi.ConvertType(out[0], new(bool)).(*bool), nil
}
