// Code generated by abigen — DO NOT EDIT.
//
// Source contract : contracts/OwnershipTransfer.sol
// Regenerate with : make bindings  (see Makefile)
package contracts

import (
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// TransferRecord mirrors the TransferRecord struct in IOwnershipTransfer.sol.
type TransferRecord struct {
	From          common.Address `abi:"from"`
	To            common.Address `abi:"to"`
	TransferredAt *big.Int       `abi:"transferredAt"`
	TransferredBy common.Address `abi:"transferredBy"`
}

// OwnershipTransferABI is the JSON ABI of the deployed OwnershipTransfer contract.
const OwnershipTransferABI = `[
  {
    "inputs": [
      {"internalType": "address", "name": "absa",              "type": "address"},
      {"internalType": "address", "name": "equipmentRegistry", "type": "address"},
      {"internalType": "address", "name": "inspectionLog",     "type": "address"}
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {"internalType": "uint256", "name": "equipmentId", "type": "uint256"},
      {"internalType": "address", "name": "operator",    "type": "address"}
    ],
    "name": "assignInitialCustody",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {"internalType": "uint256", "name": "equipmentId", "type": "uint256"},
      {"internalType": "address", "name": "to",          "type": "address"}
    ],
    "name": "initiateTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "completeTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "cancelTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "getCurrentOwner",
    "outputs": [{"internalType": "address", "name": "", "type": "address"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "getTransferHistory",
    "outputs": [{
      "components": [
        {"internalType": "address", "name": "from",          "type": "address"},
        {"internalType": "address", "name": "to",            "type": "address"},
        {"internalType": "uint256", "name": "transferredAt", "type": "uint256"},
        {"internalType": "address", "name": "transferredBy", "type": "address"}
      ],
      "internalType": "struct IOwnershipTransfer.TransferRecord[]",
      "name": "",
      "type": "tuple[]"
    }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "equipmentId", "type": "uint256"}],
    "name": "getPendingTransfer",
    "outputs": [{"internalType": "address", "name": "to", "type": "address"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "name": "currentOwner",
    "outputs": [{"internalType": "address", "name": "", "type": "address"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "name": "pendingTransfer",
    "outputs": [{"internalType": "address", "name": "", "type": "address"}],
    "stateMutability": "view",
    "type": "function"
  }
]`

// ──────────────────────────────────────────────────────────────────────────────
// Binding structs
// ──────────────────────────────────────────────────────────────────────────────

type OwnershipTransfer struct {
	OwnershipTransferCaller
	OwnershipTransferTransactor
	OwnershipTransferFilterer
}

type OwnershipTransferCaller struct {
	contract *bind.BoundContract
}

type OwnershipTransferTransactor struct {
	contract *bind.BoundContract
}

type OwnershipTransferFilterer struct {
	contract *bind.BoundContract
}

// NewOwnershipTransfer creates a Go binding to the deployed OwnershipTransfer contract.
func NewOwnershipTransfer(address common.Address, backend bind.ContractBackend) (*OwnershipTransfer, error) {
	parsed, err := abi.JSON(strings.NewReader(OwnershipTransferABI))
	if err != nil {
		return nil, err
	}
	contract := bind.NewBoundContract(address, parsed, backend, backend, backend)
	return &OwnershipTransfer{
		OwnershipTransferCaller:     OwnershipTransferCaller{contract: contract},
		OwnershipTransferTransactor: OwnershipTransferTransactor{contract: contract},
		OwnershipTransferFilterer:   OwnershipTransferFilterer{contract: contract},
	}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Transactor methods
// ──────────────────────────────────────────────────────────────────────────────

// AssignInitialCustody calls assignInitialCustody(uint256,address). Caller must hold ABSA_ROLE.
func (t *OwnershipTransferTransactor) AssignInitialCustody(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
	operator common.Address,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "assignInitialCustody", equipmentId, operator)
}

// InitiateTransfer calls initiateTransfer(uint256,address).
// Caller must be the current custodian and hold OPERATOR_ROLE.
func (t *OwnershipTransferTransactor) InitiateTransfer(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
	to common.Address,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "initiateTransfer", equipmentId, to)
}

// CompleteTransfer calls completeTransfer(uint256). Caller must be the current custodian.
func (t *OwnershipTransferTransactor) CompleteTransfer(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "completeTransfer", equipmentId)
}

// CancelTransfer calls cancelTransfer(uint256). Caller must be the current custodian.
func (t *OwnershipTransferTransactor) CancelTransfer(
	opts *bind.TransactOpts,
	equipmentId *big.Int,
) (*types.Transaction, error) {
	return t.contract.Transact(opts, "cancelTransfer", equipmentId)
}

// ──────────────────────────────────────────────────────────────────────────────
// Caller methods
// ──────────────────────────────────────────────────────────────────────────────

// GetCurrentOwner calls getCurrentOwner(uint256).
func (c *OwnershipTransferCaller) GetCurrentOwner(opts *bind.CallOpts, equipmentId *big.Int) (common.Address, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getCurrentOwner", equipmentId); err != nil {
		return common.Address{}, err
	}
	return *abi.ConvertType(out[0], new(common.Address)).(*common.Address), nil
}

// GetTransferHistory calls getTransferHistory(uint256) and decodes the tuple[] slice.
func (c *OwnershipTransferCaller) GetTransferHistory(
	opts *bind.CallOpts,
	equipmentId *big.Int,
) ([]TransferRecord, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getTransferHistory", equipmentId); err != nil {
		return nil, err
	}
	result := abi.ConvertType(out[0], new([]TransferRecord)).(*[]TransferRecord)
	return *result, nil
}

// GetPendingTransfer calls getPendingTransfer(uint256).
// Returns address(0) when there is no pending transfer.
func (c *OwnershipTransferCaller) GetPendingTransfer(opts *bind.CallOpts, equipmentId *big.Int) (common.Address, error) {
	var out []interface{}
	if err := c.contract.Call(opts, &out, "getPendingTransfer", equipmentId); err != nil {
		return common.Address{}, err
	}
	return *abi.ConvertType(out[0], new(common.Address)).(*common.Address), nil
}
